services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ChangeIt1
    healthcheck:
      test: '/opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P ChangeIt1 -Q "SELECT @@VERSION;"'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s


  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    command: '/opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P ChangeIt1 -l 90 -Q "DROP DATABASE IF EXISTS dbdeadlock; CREATE DATABASE dbdeadlock;"'
    depends_on:
      mssql:
        condition: service_healthy